### ISSUE TITLE
Return code "continue" received from GAMS via socket communication is typecasted to int without assert

### ISSUE THREAD

**Issue by grecht** [GAMS-dev/gamspy#13]
See title. This has led to an issue for which I do not know the reason. Presumably there is some issue with the set records.

```
Traceback (most recent call last):
  File "/scratch/ws/m1/rech_ge-esom-reactive/esom-reactive/src/run_acq_sequentially.py", line 224, in <module>
    main()
  File "/scratch/ws/m1/rech_ge-esom-reactive/esom-reactive/src/run_acq_sequentially.py", line 215, in main
    run_snapshot(mi, t, dir, gams_options, solver_options_ipopt)
  File "/scratch/ws/m1/rech_ge-esom-reactive/esom-reactive/src/run_acq_sequentially.py", line 130, in run_snapshot
    ct_t, problem, objective = build.build_ac(ct_t, mi_t)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/ws/m1/rech_ge-esom-reactive/metis/metis/build.py", line 340, in build_ac
    _build_core(ct, mi, reactive_power=True)
  File "/scratch/ws/m1/rech_ge-esom-reactive/metis/metis/build.py", line 436, in _build_core
    common.sets(ct, mi)
  File "/scratch/ws/m1/rech_ge-esom-reactive/metis/metis/model/common.py", line 6, in sets
    ct.addSet("T", description="snapshots", records=mi.snapshots)
  File "/lustre/exa5/home/rech_ge/miniforge3/envs/esom-reactive/lib/python3.12/site-packages/gamspy/_container.py", line 871, in addSet
    return gp.Set(
           ^^^^^^^
  File "/lustre/exa5/home/rech_ge/miniforge3/envs/esom-reactive/lib/python3.12/site-packages/gamspy/_symbols/set.py", line 652, in __init__
    self.setRecords(records, uels_on_axes=uels_on_axes)
  File "/lustre/exa5/home/rech_ge/miniforge3/envs/esom-reactive/lib/python3.12/site-packages/gamspy/_symbols/set.py", line 792, in setRecords
    self.container._synch_with_gams(gams_to_gamspy=self._is_miro_input)
  File "/lustre/exa5/home/rech_ge/miniforge3/envs/esom-reactive/lib/python3.12/site-packages/gamspy/_container.py", line 516, in _synch_with_gams
    summary = runner.run(relaxed_domain_mapping, gams_to_gamspy)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/exa5/home/rech_ge/miniforge3/envs/esom-reactive/lib/python3.12/site-packages/gamspy/_backend/local.py", line 82, in run
    self.execute_gams(gams_string, gams_to_gamspy)
  File "/lustre/exa5/home/rech_ge/miniforge3/envs/esom-reactive/lib/python3.12/site-packages/gamspy/_backend/local.py", line 103, in execute_gams
    self.container._send_job(self.job_name, self.pf_file, self.output)
  File "/lustre/exa5/home/rech_ge/miniforge3/envs/esom-reactive/lib/python3.12/site-packages/gamspy/_container.py", line 365, in _send_job
    check_response(response, job_name)
  File "/lustre/exa5/home/rech_ge/miniforge3/envs/esom-reactive/lib/python3.12/site-packages/gamspy/_container.py", line 174, in check_response
    return_code = int(value)
                  ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'continue'

```

**Comment by mabdullahsoyturk** [comment]
Socket communication has been changed significantly since the time this behavior was observed. Feel free to reopen it if you encounter it.
